---
Resources:
  PinpointApp:
    Type: AWS::Pinpoint::App
    Properties:
      Name: foobar
  PinpointAPNSChannel:
    Type: AWS::Pinpoint::APNSChannel
    Properties:
      TokenKey: b@dP@$sW0rD
      ApplicationId: !Ref PinpointApp
