---
Resources:
  ManagedPolicyFail:
    Type: AWS::IAM::ManagedPolicy 
    Properties:
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: Allow
            Action: "iam:PassRole"
            Resource: "*"
